# Todos los servicios montarán el volumen de la base de datos pero solo el primero la creará, si no está creada. Es para evitar race conditions. Esto se resuelve en la implementación de shared/database/src/connection.ts 
# Se usa el concepto de idempotencia... ejecutas algo muchas veces y siempre obtienes el mismo resultado

version: '3.8'

services:
  auth-service:
    build: ./packages/backend/auth-service
    ports:
      - "3002:3002"
    volumes:
      - db-data:/app/data
    environment:
      - DB_PATH=/app/data/transcendence.db
      - PORT=3002
  
  user-service:
    build: ./packages/backend/user-service
    ports:
      - "3003:3003"
    volumes:
      - db-data:/app/data
    environment:
      - DB_PATH=/app/data/transcendence.db
      - PORT=3003
  
  game-service:
    build: ./packages/backend/game-service
    ports:
      - "3004:3004"
    volumes:
      - db-data:/app/data
    environment:
      - DB_PATH=/app/data/transcendence.db
      - PORT=3004

volumes:
  db-data: ./db-data