packages:
  - packages/frontend
  - packages/shared
  - packages/user
  - packages/auth
  - packages/game
  - packages/images
  - packages/gateway
  - packages/comms

ignoredBuiltDependencies:
  - babylonjs

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
